## panic

panic 是 Go 程序在运行时出现的一个异常情况。如果异常出现了，但没有被捕获并恢复，Go 程序的执行就会被终止，即便出现异常的位置不在主 Goroutine 中也会这样

在 Go 中，panic 主要有两类来源，一类是来自 Go 运行时，另一类则是 Go 开发人员通过 panic 函数主动触发的。无论是哪种，一旦 panic 被触发，后续 Go 程序的执行过程都是一样的，这个过程被 Go 语言称为 panicking

```go
// enter main
// enter foo
// enter bar
// panic: panic occurs in bar

func main() {
	fmt.Println("enter main")
	foo()
	fmt.Println("exit main")
}

func foo() {
	fmt.Println("enter foo")
	bar()
	fmt.Println("exit foo")
}

func bar() {
	fmt.Println("enter bar")
	panic("panic occurs in bar")
	zoo()
	fmt.Println("exit bar")
}

func zoo() {
	fmt.Println("enter zoo")
	fmt.Println("exit zoo")
}
```

bar 函数调用 panic 函数之后，它自身的执行就此停止了，代码就没有继续进入 zoo 函数执行。并且，bar 函数没有捕捉这个 panic，这样这个 panic 就会沿着函数调用栈向上走，来到了 bar 函数的调用者 foo 函数中，foo 函数的执行也被停止了。由于 foo 函数也没有捕捉 panic，于是 panic 继续沿着函数调用栈向上走，来到了 foo 函数的调用者 main 函数中。同理，main 函数的执行也被终止了

Go 也提供了捕捉 panic 并恢复程序正常执行秩序的方法。在触发 panic 的 bar 函数中，对 panic 进行捕捉并恢复

recover 是内置的专门用于恢复 panic 的函数，它必须被放在一个 defer 函数中才能生效。如果 recover 捕捉到 panic，它就会返回以 panic 的具体内容为错误上下文信息的错误值。如果没有 panic 发生，那么 recover 将返回 nil。而且，如果 panic 被 recover 捕捉到，panic 引发的 panicking 过程就会停止

```go
// enter main
// enter foo
// enter bar
// recover the panic: panic occurs in bar
// exit foo
// exit main

func bar() {
	defer func() {
		if e := recover(); e != nil {
			fmt.Println("recover the panic:", e)
		}
	}()
	fmt.Println("enter bar")
	panic("panic occurs in bar")
	zoo()
	fmt.Println("exit bar")
}
```

当 bar 函数调用 panic 函数触发异常后，bar 函数的执行就会被中断。但这一次，在代码执行流回到 bar 函数调用者之前，bar 函数中的 derfer 函数就会被执行。这个匿名函数会调用 recover 把刚刚触发的 panic 恢复。这样，panic 还没等沿着函数栈向上走，就被消除了

## 处理 panic

其实，我们不需要在所有的地方都应对 panic。首先，很多函数根本不会出现 panic 情况，而且 defer 函数也会带来性能开销

### 忍受度

不同应用对异常引起的程序崩溃退出的忍受度是不一样的。比如，一个单次运行于控制台窗口中的命令行交互类程序，和一个常驻内存的后端 HTTP 服务器程序。标准库提供的 http server，每个客户端连接都使用一个单独的 Goroutine 进行处理的并发处理模型

```go
// $GOROOT/src/net/http/server.go

func (c *conn) serve(ctx context.Context) {
	c.remoteAddr = c.rwc.RemoteAddr().String()
	ctx = context.WithValue(ctx, LocalAddrContextKey, c.rwc.LocalAddr())
	defer func() {
		if err := recover(); err != nil && err != ErrAbortHandler {
			const size = 64 << 10
			buf := make([]byte, size)
			buf = buf[:runtime.Stack(buf, false)]
			c.server.logf("http: panic serving %v: %v\n%s", c.remoteAddr, err, buf)
		}
		if !c.hijacked() {
			c.close()
			c.setState(c.rwc, StateClosed)
		}
	}()
    
    // ignore
}
```

### 潜在 bug 提示

```go
func (w *reflectWithString) resolve() error {
	// ignore
	switch w.v.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		w.s = strconv.FormatInt(w.v.Int(), 10)
		return nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		w.s = strconv.FormatUint(w.v.Uint(), 10)
		return nil
	}
	panic("unexpected map key type")
}
```

### 异常与错误

在 Go 中，作为 API 开发者，一定不要将 panic 当作错误返回给 API 调用者

## defer

只有在函数和方法内部才能使用 defer，defer 后面只能接函数或方法，这些函数被称为 deferred 函数。defer 将它们注册到其所在 Goroutine 中，用于存放 deferred 函数的栈数据结构中。这些 deferred 函数将在执行 defer 的函数退出前，按后进先出的顺序被程序调度执行

![[Pasted image 20230219114748.png]]

无论是执行到函数体尾部返回，还是在某个错误处理分支显式 return，又或是出现 panic，已经存储到 deferred 函数栈中的函数，都会被调度执行

### 注意事项

明确哪些函数可以作为 deferred 函数。对于自定义的函数或方法，defer 可以给与无条件的支持，但是对于有返回值的自定义函数或方法，返回值会在 deferred 函数被调度执行的时候被自动丢弃。append、cap、len、make、new、imag 等内置函数都是不能直接作为 deferred 函数的，而 close、copy、delete、print、recover 等内置函数则可以直接被 defer 设置为 deferred 函数

对于那些不能直接作为 deferred 函数的内置函数，可以使用一个包裹它的匿名函数来间接满足要求

```go
defer func() {
    _ = append(s, 10)
}()
```

注意 defer 关键字后面表达式的求值时机。defer 关键字后面的表达式，是在将 deferred 函数注册到 deferred 函数栈的时候进行求值的

```go
// 入栈顺序：
// fmt.Println(0)
// fmt.Println(1)
// fmt.Println(2)
func foo1() {
	for i := 0; i < 3; i++ {
		defer fmt.Println(i)
	}
}

// 入栈顺序：
// func(0)
// func(1)
// func(2)
func foo2() {
	for i := 0; i < 3; i++ {
		defer func(n int) {
			fmt.Println(n)
		}(i)
	}
}

// 入栈顺序：
// func()
// func()
// func()
func foo3() {
	for i := 0; i < 3; i++ {
		defer func() {
			fmt.Println(i)
		}()
	}
}

// output: 2, 1, 0
fmt.Println("foo1:")
foo1()

// output: 2, 1, 0
fmt.Println("foo2:")
foo2()

// output: 3, 3, 3
fmt.Println("foo3:")
foo3()
```

defer 带来性能损耗。在 Go 1.13 前的版本中，defer 带来的开销很大。从 Go 1.13 版本开始，Go 核心团队对 defer 性能进行了多次优化，到 Go 1.17 版本，defer 的开销已经足够小了